### PR TITLE
Update list command to save the show timetable option

### LINKED ISSUE #147: Update list command to save user prefs of showing timetable
After user inputs `list` or `list timetable` to choose the option of displaying timetable, the preference should remain the same for sesequent command results

### PR DESCRIPTION
**Pull request by fy17ohhh**
- Fixes #147
- Instead of saving the `showTimetable` option to `CommandResult`, saving it to `UserPrefs` such that in the case when user chooses to show timetable and then finds some students, the timetable will remain visible
- Update UG for list command
- Delete unnecessary Ui image as `sampleUi.png` is the same as` Ui.png`
- Fix the typo in `AddSequenceDiagram.puml`
- Adjust size of  Sequence Diagrams
- Update `Model `class method to show all students to improve readability
- Add Sequence Diagram for `list `command
image

### CODE REVIEW

**Comment by fy17ohhh** [comment]
Ready for review, please review the List Sequence Diagram to check if there are any errors
Especially for the `updateFilteredStudentList()` methods, not pretty sure if this is the correct way to show the calling of `static` variable of the `Model `class

**Comment by marclamp** [comment]
> Especially for the `updateFilteredStudentList()` methods, not pretty sure if this is the correct way to show the calling of `static` variable of the `Model `class

I believe calling static variables is underline(?), at least that's for class diagrams. 
Although maybe a more correct way is to have a separate <<class>> Model box, but since the focus in this sequence diagram is on the Logic component, may not necessarily be useful.

**Review by marclamp — COMMENTED** [review]
LGTM.

> Especially for the updateFilteredStudentList() methods, not pretty sure if this is the correct way to show the calling of static variable of the Model class

I believe calling static variables is underline(?), at least that's for class diagrams.
Although maybe a more correct way is to have a separate <> Model box, but since the focus in this sequence diagram is on the Logic component, may not necessarily be useful.

**Comment by fy17ohhh** [comment]
> LGTM.
> 
> > Especially for the updateFilteredStudentList() methods, not pretty sure if this is the correct way to show the calling of static variable of the Model class
> 
> I believe calling static variables is underline(?), at least that's for class diagrams. Although maybe a more correct way is to have a separate <> Model box, but since the focus in this sequence diagram is on the Logic component, may not necessarily be useful.

I searched through our textbook and it did not mention that we need to underline static variables for sequence diagrams, there are only rules for static methods calls tho

**Pull request merged**
