### PR TITLE
Update UML diagrams and respective DG sections to match

### PR DESCRIPTION
**Pull request by marclamp**
Add
* AddSequenceDiagram.puml
* AddSequenceDiagram.png
* StudentClassDiagram.puml
* StudentClassDiagram.png
* DG Implementation Section with Timetable Support
* Proposed Implementation for searching for common slot

image
image

### CODE REVIEW

**Comment by darryl-chan** [comment]
Change phone and address to Student ID and Telegram Handle in model diagram

**Review by tanjiajiajun — APPROVED** [review]
Nice work, LGTM

**Comment by fy17ohhh** [comment]
Comprehensible, LGTM:)

**Review by fy17ohhh — APPROVED** [review]
Comprehensible, LGTM:)

**Comment by jeremiahlzz** [comment]
#88

**Pull request merged**
